# Generated by Django 2.0.1 on 2018-06-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0004_auto_20180606_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_pharmacist',
            new_name='pharmacist',
        ),
    ]
