# Generated by Django 2.0.1 on 2018-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawakhana', '0005_auto_20180606_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, verbose_name='Username'),
        ),
    ]
